"""
T-07 acceptance test: Verify quoin/CLAUDE.md contains the new Subagent preamble
section and the Tier 1 carve-out disambiguation note for preamble.md.

Per T-07 plan:
- New ### Subagent preamble (Stage 2 of pipeline-efficiency-improvements) heading exists
- The "purely additive" phrase is present in the section
- The "GENERATED by quoin/scripts/build_preambles.py" phrase is present
- The explicit Tier 1 carve-out line for preamble.md (GENERATED disambiguation) exists
"""

import pathlib

import pytest

HERE = pathlib.Path(__file__).resolve().parent
QUOIN_DIR = HERE.parent.parent  # quoin/dev/tests/ -> quoin/dev/ -> quoin/
CLAUDE_MD = QUOIN_DIR / "CLAUDE.md"


def _read_claude_md() -> str:
    return CLAUDE_MD.read_text(encoding="utf-8")


def test_subagent_preamble_heading_exists():
    """The new ### Subagent preamble sub-section heading is present."""
    content = _read_claude_md()
    assert "### Subagent preamble (Stage 2 of pipeline-efficiency-improvements)" in content, (
        "quoin/CLAUDE.md is missing the '### Subagent preamble (Stage 2 of pipeline-efficiency-improvements)' heading"
    )


def test_subagent_preamble_purely_additive_phrase():
    """The 'purely additive' phrase is present in the preamble section."""
    content = _read_claude_md()
    assert "purely additive" in content.lower(), (
        "quoin/CLAUDE.md Subagent preamble section is missing the 'purely additive' description"
    )


def test_subagent_preamble_generated_by_phrase():
    """The 'GENERATED by quoin/scripts/build_preambles.py' phrase is present."""
    content = _read_claude_md()
    assert "GENERATED by `quoin/scripts/build_preambles.py`" in content, (
        "quoin/CLAUDE.md is missing the 'GENERATED by quoin/scripts/build_preambles.py' phrase"
    )


def test_tier1_carveout_preamble_disambiguation():
    """The Tier 1 Source files section has the preamble.md disambiguation note."""
    content = _read_claude_md()
    assert "preamble.md` (any of the 7 spawn targets" in content, (
        "quoin/CLAUDE.md is missing the Tier 1 carve-out disambiguation note for preamble.md "
        "(expected: 'preamble.md` (any of the 7 spawn targets' in Source files section)"
    )
    assert "NOT a Tier 1 hand-edited source file" in content, (
        "quoin/CLAUDE.md preamble.md carve-out note is missing 'NOT a Tier 1 hand-edited source file'"
    )
